name: Run Script
on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Script
        run: python main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: tech-books.csv
